### ISSUE TITLE
Speedify now treats this as a "Router"

### ISSUE THREAD

**Issue by spacesuitdiver** [TalalMash/Unofficial-Speedify-Installer-For-OpenWrt#16]
I was giving this a spin again, I historically had been using a Raspberry Pi but it looks like Speedify is now detecting this installation method as a "Router". I contacted support for some help because their article seems to indicate you just need an individual account and that OpenWRT routers are unsupported. Nothing about $45/mo just to use this on an unsupported device.

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/bd299608-dc3d-4e70-a4f8-00b62db18335">

What a bummer!

<img width="809" alt="image" src="https://github.com/user-attachments/assets/df353654-0a7a-439d-afd6-f5e9796f73fc">

**Comment by TalalMash** [comment]
I guess their target was mobile users with the regular users regarding traffic costs, but the Family plan exist with similar consumption and lower costs, I hope they implement monthly traffic limit for routers in the future...

It seems like they year+ delay for the official release is held back by their partner product release dates: https://speedify.com/enterprise/#poweredbyspeedify
Hopefully these won't have the additional fee...

**Comment by bt61** [comment]
Where does that "router subscription" link take you?  I've never seen any mention of a router specific subscription.

They have been advertising using a Pi as a (linux) router for years, but there are real server costs that scale with throughput, so it's also understandable that they have some limits. They said on the last livestream that the OpenWRT beta was ready for release (where??), but I don't think they have ever specifically addressed if that will be usable on standard individual plans.

**Comment by spacesuitdiver** [comment]
I did receive a support response and the router message was not why I was not connecting to Speedify.

I’m using an X3000 and at first just had the cell modem but adding a wwan I was able to get connected but no internet connection so I reset my router because tinker time was over 😅

![IMG_1691](https://github.com/user-attachments/assets/0a30dcc4-1c84-4dab-a013-8f8d920876fb)

I’ll post my network config tomorrow, I don’t want to spend a ton of time as I’ll likely switch to just two an Ethernet modem and WWAN soon.

**Comment by bt61** [comment]
Some searching revealed this page:
https://speedify.com/mvd-router-one/
as well as this preview video: https://www.youtube.com/watch?v=XQAa6SxgkyQ

That's clearly enterprise focused, and I hope what they are indicating with the $450/yr router plan they linked for you.  On the Office Hours streams they have referenced supporting OpenWRT with consumer devices such as GL.iNet routers, Raspberry Pi, and Banana Pi.  It has seemed like the OpenWRT package will be a free software and not require any different tier of service, but I'm not sure they've explicitly stated that or not.  

I guess I would not be surprised if they find the OpenWRT support as a new revenue stream rather than just a way to sell more regular subscriptions. That would explain why they have always seemed to reluctantantly discuss Smoothwan on the stream.

**Comment by umekzg** [comment]
That's a Magewell Pro Route... Still in beta, not released yet.
